// Mocks generated by Mockito 5.4.4 from annotations
// in grocery_shopper/test/inventory_location_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:grocery_shopper/models/inventory.dart' as _i2;
import 'package:grocery_shopper/models/inventory_item.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Inventory].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventory extends _i1.Mock implements _i2.Inventory {
  MockInventory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<String> get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.InventoryItem> getItemsInLocation(String? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsInLocation,
          [location],
        ),
        returnValue: <_i3.InventoryItem>[],
      ) as List<_i3.InventoryItem>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
